stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - data/tweets_suspect.csv
      - scripts/preprocess.py
    outs:
      - data/tweets_preprocessed.csv

  train:
    cmd: python scripts/train.py
    deps:
      - data/tweets_preprocessed.csv
      - scripts/train.py
    outs:
      - models/model.pkl
      - models/tfidf_vectorizer.pkl

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - models/model.pkl
      - models/tfidf_vectorizer.pkl
      - data/tweets_preprocessed.csv
      - scripts/evaluate.py
    outs:
      - confusion_matrix.png
      - courbe_roc.png
    metrics:
      - metrics.json:
          cache: false
